name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 升级到最新版本

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'  # 使用 Eclipse Temurin 替代弃用的 AdoptOpenJDK

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: false  # 启用 Gradle 依赖缓存

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleDebug  # 或改用 assembleRelease 若需发布版本

    - name: Upload APK
      uses: actions/upload-artifact@v4  # 升级到最新版本
      with:
        name: updatehelper-apk
        path: app/build/outputs/apk/debug/*.apk  # 确认路径与实际生成位置一致
